BEGIN;

-- 0) Предполагается, что таблицы существуют:
-- public.roles(id, key, name, description)
-- public.permissions(id, key, name, description)
-- public.role_permissions(role_id, permission_id)
-- public.user_roles(user_id, role_id)
-- public.users(id, employee_id, ...)
-- public."Сотрудники"(id, "должность", ...)

-- 1) Permissions: upsert по key
WITH src_permissions(key, name, description) AS (
  VALUES
    -- orders actions
    ('orders.list', 'Просмотр списка заявок', 'Действие'),
    ('orders.view', 'Просмотр карточки заявки', 'Действие'),
    ('orders.create', 'Создание заявок', 'Действие'),
    ('orders.edit', 'Редактирование заявок', 'Действие'),
    ('orders.delete', 'Удаление заявок', 'Действие'),
    ('orders.purchases.create', 'Создание закупок из заявок', 'Действие'),
    ('orders.print', 'Печать заявки', 'Действие'),
    ('orders.export.pdf', 'Экспорт заявки в PDF', 'Действие'),
    ('orders.export.excel', 'Экспорт заявки в Excel', 'Действие'),
    ('orders.export.word', 'Экспорт заявки в Word', 'Действие'),
    ('orders.missing_products.manage', 'Управление недостающими товарами заявки', 'Действие'),
    ('orders.attachments.view', 'Просмотр документов заявки', 'Действие'),
    ('orders.attachments.upload', 'Загрузка документов заявки', 'Действие'),
    ('orders.attachments.delete', 'Удаление документов заявки', 'Действие'),

    -- purchases actions
    ('purchases.list', 'Просмотр списка закупок', 'Действие'),
    ('purchases.view', 'Просмотр карточки закупки', 'Действие'),
    ('purchases.create', 'Создание закупки', 'Действие'),
    ('purchases.edit', 'Редактирование закупки', 'Действие'),
    ('purchases.delete', 'Удаление закупки', 'Действие'),
    ('purchases.order.view', 'Открыть заявку из закупки', 'Действие'),
    ('purchases.print', 'Печать закупки', 'Действие'),
    ('purchases.export.pdf', 'Экспорт закупки в PDF', 'Действие'),
    ('purchases.export.excel', 'Экспорт закупки в Excel', 'Действие'),
    ('purchases.export.word', 'Экспорт закупки в Word', 'Действие'),
    ('purchases.attachments.view', 'Просмотр документов закупки', 'Действие'),
    ('purchases.attachments.upload', 'Загрузка документов закупки', 'Действие'),
    ('purchases.attachments.delete', 'Удаление документов закупки', 'Действие'),

    -- shipments actions
    ('shipments.list', 'Просмотр списка отгрузок', 'Действие'),
    ('shipments.view', 'Просмотр карточки отгрузки', 'Действие'),
    ('shipments.create', 'Создание отгрузок', 'Действие'),
    ('shipments.edit', 'Редактирование отгрузок', 'Действие'),
    ('shipments.delete', 'Удаление отгрузок', 'Действие'),
    ('shipments.order.view', 'Перейти к заявке из отгрузки', 'Действие'),
    ('shipments.track', 'Отследить груз (отгрузки)', 'Действие'),
    ('shipments.print', 'Печать документов отгрузки', 'Действие'),
    ('shipments.export.excel', 'Экспорт отгрузок в Excel', 'Действие'),
    ('shipments.import.excel', 'Импорт отгрузок из Excel', 'Действие'),
    ('shipments.positions.view', 'Просмотр состава отгрузки', 'Действие'),
    ('shipments.attachments.view', 'Просмотр документов отгрузки', 'Действие'),
    ('shipments.attachments.upload', 'Загрузка документов отгрузки', 'Действие'),
    ('shipments.attachments.delete', 'Удаление документов отгрузки', 'Действие'),

    -- transport actions
    ('transport.list', 'Просмотр списка транспортных компаний', 'Действие'),
    ('transport.view', 'Просмотр карточки транспортной компании', 'Действие'),
    ('transport.create', 'Создание транспортных компаний', 'Действие'),
    ('transport.edit', 'Редактирование транспортных компаний', 'Действие'),
    ('transport.delete', 'Удаление транспортных компаний', 'Действие'),
    ('transport.stats.view', 'Просмотр статистики транспортной компании', 'Действие'),
    ('transport.active_shipments.view', 'Просмотр вкладки активных отгрузок (ТК)', 'Действие'),
    ('transport.recent_shipments.view', 'Просмотр вкладки последних отгрузок (ТК)', 'Действие'),
    ('transport.shipments.history.view', 'Просмотр вкладки истории отгрузок (ТК)', 'Действие'),
    ('transport.shipments.months.view', 'Просмотр вкладки по месяцам (ТК)', 'Действие'),
    ('transport.attachments.view', 'Просмотр документов транспортной компании', 'Действие'),
    ('transport.attachments.upload', 'Загрузка документов транспортной компании', 'Действие'),
    ('transport.attachments.delete', 'Удаление документов транспортной компании', 'Действие'),

    -- archive actions
    ('archive.orders.list', 'Просмотр архивных заявок', 'Действие'),
    ('archive.orders.view', 'Переход в карточку заявки из архива', 'Действие'),
    ('archive.purchases.list', 'Просмотр архивных закупок', 'Действие'),
    ('archive.purchases.view', 'Переход в карточку закупки из архива', 'Действие'),
    ('archive.shipments.list', 'Просмотр архивных отгрузок', 'Действие'),
    ('archive.shipments.view', 'Переход в карточку отгрузки из архива', 'Действие'),
    ('archive.payments.list', 'Просмотр архивных выплат', 'Действие'),
    ('archive.finance.list', 'Просмотр архивных финансов', 'Действие'),

    -- warehouse actions
    ('warehouse.list', 'Просмотр списка склада', 'Действие'),
    ('warehouse.view', 'Просмотр карточки товара на складе', 'Действие'),
    ('warehouse.create', 'Создание товара на складе', 'Действие'),
    ('warehouse.edit', 'Изменение товара', 'Действие'),
    ('warehouse.delete', 'Удаление товара со склада', 'Действие'),
    ('warehouse.movement.create', 'Создание движений склада (приход/расход)', 'Действие'),
    ('warehouse.stock.adjust', 'Корректировка остатков товара', 'Действие'),
    ('warehouse.movements.view', 'Просмотр движений товаров', 'Действие'),
    ('warehouse.critical.view', 'Просмотр критических остатков', 'Действие'),
    ('warehouse.export.excel', 'Экспорт склада в Excel', 'Действие'),
    ('warehouse.import.excel', 'Импорт склада из Excel', 'Действие'),
    ('warehouse.waiting_orders.view', 'Просмотр ожидающих заявок по товару на складе', 'Действие'),
    ('warehouse.pending_purchases.view', 'Просмотр ожидаемых поступлений по товару на складе', 'Действие'),
    ('warehouse-products.attachments.view', 'Просмотр документов товаров на складе', 'Действие'),
    ('warehouse-products.attachments.upload', 'Загрузка документов товаров на складе', 'Действие'),
    ('warehouse-products.attachments.delete', 'Удаление документов товаров на складе', 'Действие'),

    -- clients actions
    ('clients.list', 'Просмотр списка клиентов', 'Действие'),
    ('clients.view', 'Просмотр карточки клиента', 'Действие'),
    ('clients.orders_history.view', 'Просмотр истории заказов клиента', 'Действие'),
    ('clients.orders_history.order.view', 'Просмотр заявки из карточки клиента', 'Действие'),
    ('clients.attachments.view', 'Просмотр документов клиентов', 'Действие'),
    ('clients.attachments.upload', 'Загрузка документов клиентов', 'Действие'),
    ('clients.attachments.delete', 'Удаление документов клиентов', 'Действие'),
    ('clients.create', 'Создание клиентов', 'Действие'),
    ('clients.edit', 'Редактирование клиентов', 'Действие'),
    ('clients.delete', 'Удаление клиентов', 'Действие'),

    -- suppliers actions
    ('suppliers.list', 'Просмотр списка поставщиков', 'Действие'),
    ('suppliers.view', 'Просмотр карточки поставщика', 'Действие'),
    ('suppliers.create', 'Создание поставщиков', 'Действие'),
    ('suppliers.edit', 'Редактирование поставщиков', 'Действие'),
    ('suppliers.delete', 'Удаление поставщиков', 'Действие'),
    ('suppliers.orders_history.view', 'Просмотр истории заказов поставщика', 'Действие'),
    ('suppliers.assortment.view', 'Просмотр ассортимента поставщика', 'Действие'),
    ('suppliers.purchases_history.view', 'Просмотр истории закупок поставщика', 'Действие'),
    ('suppliers.assortment.add_product', 'Добавление товара в ассортимент поставщика', 'Действие'),
    ('suppliers.purchases.create', 'Создание закупки из карточки поставщика', 'Действие'),
    ('suppliers.attachments.view', 'Просмотр документов поставщика', 'Действие'),
    ('suppliers.attachments.upload', 'Загрузка документов поставщика', 'Действие'),
    ('suppliers.attachments.delete', 'Удаление документов поставщика', 'Действие'),

    -- categories actions
    ('categories.list', 'Просмотр списка категорий', 'Действие'),
    ('categories.view', 'Просмотр карточки категории', 'Действие'),
    ('categories.create', 'Создание категорий', 'Действие'),
    ('categories.edit', 'Редактирование категорий', 'Действие'),
    ('categories.delete', 'Удаление категорий', 'Действие'),
    ('categories.disable', 'Отключение категорий', 'Действие'),

    -- managers actions
    ('managers.list', 'Просмотр списка сотрудников', 'Действие'),
    ('managers.view', 'Просмотр карточки сотрудника', 'Действие'),
    ('managers.create', 'Создание сотрудников', 'Действие'),
    ('managers.edit', 'Редактирование сотрудников', 'Действие'),
    ('managers.delete', 'Удаление сотрудников', 'Действие'),
    ('managers.attachments.view', 'Просмотр документов сотрудников', 'Действие'),
    ('managers.attachments.upload', 'Загрузка документов сотрудников', 'Действие'),
    ('managers.attachments.delete', 'Удаление документов сотрудников', 'Действие'),

    -- missing-products actions
    ('missing_products.list', 'Просмотр списка недостающих товаров', 'Действие'),
    ('missing_products.create', 'Создание недостающих товаров', 'Действие'),
    ('missing_products.edit', 'Редактирование недостающих товаров', 'Действие'),
    ('missing_products.order.view', 'Просмотр заявки из недостающих товаров', 'Действие'),
    ('missing_products.delete', 'Удаление недостающих товаров', 'Действие'),

    -- products actions
    ('products.list', 'Просмотр списка товаров', 'Действие'),
    ('products.view', 'Просмотр карточки товара', 'Действие'),
    ('products.create', 'Создание товаров', 'Действие'),
    ('products.edit', 'Редактирование товаров', 'Действие'),
    ('products.delete', 'Удаление товаров', 'Действие'),
    ('products.price_history.view', 'Просмотр истории цен товаров', 'Действие'),
    ('products.import', 'Импорт товаров из Excel', 'Действие'),
    ('products.export.excel', 'Экспорт товаров в Excel', 'Действие'),
    ('products.attachments.view', 'Просмотр документов товаров', 'Действие'),
    ('products.attachments.upload', 'Загрузка документов товаров', 'Действие'),
    ('products.attachments.delete', 'Удаление документов товаров', 'Действие'),

    -- dashboard actions
    ('dashboard.view', 'Доступ к странице "Дашборд"', 'Специальное право'),
    ('dashboard.quick_actions.view', 'Просмотр блока "Быстрые действия" на дашборде', 'Специальное право'),
    ('dashboard.summary.view', 'Просмотр блока "Сводка" на дашборде', 'Специальное право'),
    ('dashboard.sales_chart.view', 'Просмотр блока "Продажи" на дашборде', 'Специальное право'),
    ('dashboard.stock_by_category.view', 'Просмотр блока "Склад по категориям" на дашборде', 'Специальное право'),
    ('dashboard.recent_orders.view', 'Просмотр блока "Последние заказы" на дашборде', 'Специальное право'),
    ('dashboard.warehouse_movements.view', 'Просмотр блока "Движения по складу" на дашборде', 'Специальное право'),
    ('dashboard.finance_chart.view', 'Просмотр блока "Финансы" на дашборде', 'Специальное право'),
    ('dashboard.top_products.view', 'Просмотр блока "Топ товары" на дашборде', 'Специальное право'),
    ('dashboard.top_clients.view', 'Просмотр блока "Топ клиенты" на дашборде', 'Специальное право'),
    ('dashboard.transport_performance.view', 'Просмотр блока "Логистика" на дашборде', 'Специальное право'),

    -- reports actions
    ('reports.overview.view', 'Просмотр вкладки "Общий обзор" в отчетах', 'Специальное право'),
    ('reports.sales.view', 'Просмотр вкладки "Продажи" в отчетах', 'Специальное право'),
    ('reports.products.view', 'Просмотр вкладки "Товары" в отчетах', 'Специальное право'),
    ('reports.clients.view', 'Просмотр вкладки "Клиенты" в отчетах', 'Специальное право'),
    ('reports.logistics.view', 'Просмотр вкладки "Логистика" в отчетах', 'Специальное право'),
    ('reports.custom.view', 'Просмотр вкладки "Пользовательские отчеты"', 'Специальное право'),
    ('reports.custom.clients_analysis.view', 'Просмотр отчета "Анализ контрагентов"', 'Специальное право'),
    ('reports.custom.clients_analysis.export.word', 'Экспорт отчета "Анализ контрагентов" в Word', 'Специальное право'),
    ('reports.custom.clients_analysis.export.excel', 'Экспорт отчета "Анализ контрагентов" в Excel', 'Специальное право'),
    ('reports.custom.missing_analysis.view', 'Просмотр отчета "Анализ недостач"', 'Специальное право'),
    ('reports.custom.missing_analysis.export.word', 'Экспорт отчета "Анализ недостач" в Word', 'Специальное право'),
    ('reports.custom.missing_analysis.export.excel', 'Экспорт отчета "Анализ недостач" в Excel', 'Специальное право'),
    ('reports.custom.suppliers_analysis.view', 'Просмотр отчета "Анализ поставщиков"', 'Специальное право'),
    ('reports.custom.suppliers_analysis.export.word', 'Экспорт отчета "Анализ поставщиков" в Word', 'Специальное право'),
    ('reports.custom.suppliers_analysis.export.excel', 'Экспорт отчета "Анализ поставщиков" в Excel', 'Специальное право'),
    ('reports.custom.warehouse_movements.view', 'Просмотр отчета "Движения склада"', 'Специальное право'),
    ('reports.custom.warehouse_movements.export.word', 'Экспорт отчета "Движения склада" в Word', 'Специальное право'),
    ('reports.custom.warehouse_movements.export.excel', 'Экспорт отчета "Движения склада" в Excel', 'Специальное право'),
    ('reports.custom.sales_by_period.view', 'Просмотр отчета "Продажи по периодам"', 'Специальное право'),
    ('reports.custom.sales_by_period.export.word', 'Экспорт отчета "Продажи по периодам" в Word', 'Специальное право'),
    ('reports.custom.sales_by_period.export.excel', 'Экспорт отчета "Продажи по периодам" в Excel', 'Специальное право'),
    ('reports.custom.transport_stats.view', 'Просмотр отчета "Статистика ТК"', 'Специальное право'),
    ('reports.custom.transport_stats.export.word', 'Экспорт отчета "Статистика ТК" в Word', 'Специальное право'),
    ('reports.custom.transport_stats.export.excel', 'Экспорт отчета "Статистика ТК" в Excel', 'Специальное право'),
    ('reports.custom.finance_overview.view', 'Просмотр отчета "Финансовый обзор"', 'Специальное право'),
    ('reports.custom.finance_overview.export.word', 'Экспорт отчета "Финансовый обзор" в Word', 'Специальное право'),
    ('reports.custom.finance_overview.export.excel', 'Экспорт отчета "Финансовый обзор" в Excel', 'Специальное право'),
    ('reports.custom.employee_performance.view', 'Просмотр отчета "Эффективность сотрудников"', 'Специальное право'),
    ('reports.custom.employee_performance.export.word', 'Экспорт отчета "Эффективность сотрудников" в Word', 'Специальное право'),
    ('reports.custom.employee_performance.export.excel', 'Экспорт отчета "Эффективность сотрудников" в Excel', 'Специальное право'),

    -- special
    ('admin.users', 'Управление пользователями', 'Специальное право'),
    ('admin.roles', 'Управление ролями', 'Специальное право'),
    ('admin.settings', 'Управление настройками системы', 'Специальное право')
)
INSERT INTO public.permissions(key, name, description)
SELECT key, name, description
FROM src_permissions
ON CONFLICT (key) DO UPDATE
SET
  name = EXCLUDED.name,
  description = EXCLUDED.description;

-- 2) Roles: upsert по key (добавлен accountant)
WITH src_roles(key, name) AS (
  VALUES
    ('director', 'Главный директор'),
    ('manager', 'Менеджер по продажам'),
    ('purchaser', 'Менеджер по закупкам'),
    ('warehouse_manager', 'Заведующий складом'),
    ('logistics', 'Логист'),
    ('viewer', 'Наблюдатель'),
    ('accountant', 'Бухгалтер')
)
INSERT INTO public.roles(key, name)
SELECT key, name
FROM src_roles
ON CONFLICT (key) DO UPDATE
SET
  name = EXCLUDED.name;

-- 3) Role permissions: (role_key, perm_key) -> role_id/perm_id
WITH src_role_perms(role_key, perm_key) AS (
  VALUES
    -- director = all permissions
    ('director', 'orders.list'),
    ('director', 'orders.view'),
    ('director', 'orders.create'),
    ('director', 'orders.edit'),
    ('director', 'orders.delete'),
    ('director', 'orders.purchases.create'),
    ('director', 'orders.print'),
    ('director', 'orders.export.pdf'),
    ('director', 'orders.export.excel'),
    ('director', 'orders.export.word'),
    ('director', 'orders.missing_products.manage'),
    ('director', 'orders.attachments.view'),
    ('director', 'orders.attachments.upload'),
    ('director', 'orders.attachments.delete'),
    ('director', 'purchases.list'),
    ('director', 'purchases.view'),
    ('director', 'purchases.create'),
    ('director', 'purchases.edit'),
    ('director', 'purchases.delete'),
    ('director', 'purchases.order.view'),
    ('director', 'purchases.print'),
    ('director', 'purchases.export.pdf'),
    ('director', 'purchases.export.excel'),
    ('director', 'purchases.export.word'),
    ('director', 'purchases.attachments.view'),
    ('director', 'purchases.attachments.upload'),
    ('director', 'purchases.attachments.delete'),
    ('director', 'shipments.list'),
    ('director', 'shipments.view'),
    ('director', 'shipments.create'),
    ('director', 'shipments.edit'),
    ('director', 'shipments.delete'),
    ('director', 'shipments.ship'),
    ('director', 'shipments.order.view'),
    ('director', 'shipments.track'),
    ('director', 'shipments.print'),
    ('director', 'shipments.export.excel'),
    ('director', 'shipments.import.excel'),
    ('director', 'shipments.positions.view'),
    ('director', 'shipments.attachments.view'),
    ('director', 'shipments.attachments.upload'),
    ('director', 'shipments.attachments.delete'),
    ('director', 'archive.orders.list'),
    ('director', 'archive.orders.view'),
    ('director', 'archive.purchases.list'),
    ('director', 'archive.purchases.view'),
    ('director', 'archive.shipments.list'),
    ('director', 'archive.shipments.view'),
    ('director', 'archive.payments.list'),
    ('director', 'archive.finance.list'),
    ('director', 'warehouse.list'),
    ('director', 'warehouse.view'),
    ('director', 'warehouse.create'),
    ('director', 'warehouse.edit'),
    ('director', 'warehouse.delete'),
    ('director', 'warehouse.movement.create'),
    ('director', 'warehouse.stock.adjust'),
    ('director', 'warehouse.movements.view'),
    ('director', 'warehouse.critical.view'),
    ('director', 'warehouse.export.excel'),
    ('director', 'warehouse.import.excel'),
    ('director', 'warehouse.waiting_orders.view'),
    ('director', 'warehouse.pending_purchases.view'),
    ('director', 'warehouse-products.attachments.view'),
    ('director', 'warehouse-products.attachments.upload'),
    ('director', 'warehouse-products.attachments.delete'),
    ('director', 'clients.list'),
    ('director', 'clients.view'),
    ('director', 'clients.orders_history.view'),
    ('director', 'clients.orders_history.order.view'),
    ('director', 'clients.attachments.view'),
    ('director', 'clients.attachments.upload'),
    ('director', 'clients.attachments.delete'),
    ('director', 'clients.create'),
    ('director', 'clients.edit'),
    ('director', 'clients.delete'),
    ('director', 'suppliers.list'),
    ('director', 'suppliers.view'),
    ('director', 'suppliers.create'),
    ('director', 'suppliers.edit'),
    ('director', 'suppliers.delete'),
    ('director', 'suppliers.orders_history.view'),
    ('director', 'suppliers.assortment.view'),
    ('director', 'suppliers.purchases_history.view'),
    ('director', 'suppliers.assortment.add_product'),
    ('director', 'suppliers.purchases.create'),
    ('director', 'suppliers.attachments.view'),
    ('director', 'suppliers.attachments.upload'),
    ('director', 'suppliers.attachments.delete'),
    ('director', 'categories.list'),
    ('director', 'categories.view'),
    ('director', 'categories.create'),
    ('director', 'categories.edit'),
    ('director', 'categories.delete'),
    ('director', 'categories.disable'),
    ('director', 'missing_products.list'),
    ('director', 'missing_products.create'),
    ('director', 'missing_products.edit'),
    ('director', 'missing_products.order.view'),
    ('director', 'missing_products.delete'),
    ('director', 'products.list'),
    ('director', 'products.view'),
    ('director', 'products.create'),
    ('director', 'products.edit'),
    ('director', 'products.delete'),
    ('director', 'products.price_history.view'),
    ('director', 'products.attachments.view'),
    ('director', 'products.import'),
    ('director', 'products.export.excel'),
    ('director', 'dashboard.view'),
    ('director', 'dashboard.quick_actions.view'),
    ('director', 'dashboard.summary.view'),
    ('director', 'dashboard.sales_chart.view'),
    ('director', 'dashboard.stock_by_category.view'),
    ('director', 'dashboard.recent_orders.view'),
    ('director', 'dashboard.warehouse_movements.view'),
    ('director', 'dashboard.finance_chart.view'),
    ('director', 'dashboard.top_products.view'),
    ('director', 'dashboard.top_clients.view'),
    ('director', 'dashboard.transport_performance.view'),
    ('director', 'admin.users'),
    ('director', 'admin.roles'),
    ('director', 'admin.settings'),
    ('director', 'reports.overview.view'),
    ('director', 'reports.sales.view'),
    ('director', 'reports.products.view'),
    ('director', 'reports.clients.view'),
    ('director', 'reports.logistics.view'),
    ('director', 'reports.custom.view'),
    ('director', 'reports.custom.clients_analysis.view'),
    ('director', 'reports.custom.clients_analysis.export.word'),
    ('director', 'reports.custom.clients_analysis.export.excel'),
    ('director', 'reports.custom.missing_analysis.view'),
    ('director', 'reports.custom.missing_analysis.export.word'),
    ('director', 'reports.custom.missing_analysis.export.excel'),
    ('director', 'reports.custom.suppliers_analysis.view'),
    ('director', 'reports.custom.suppliers_analysis.export.word'),
    ('director', 'reports.custom.suppliers_analysis.export.excel'),
    ('director', 'reports.custom.warehouse_movements.view'),
    ('director', 'reports.custom.warehouse_movements.export.word'),
    ('director', 'reports.custom.warehouse_movements.export.excel'),
    ('director', 'reports.custom.sales_by_period.view'),
    ('director', 'reports.custom.sales_by_period.export.word'),
    ('director', 'reports.custom.sales_by_period.export.excel'),
    ('director', 'reports.custom.transport_stats.view'),
    ('director', 'reports.custom.transport_stats.export.word'),
    ('director', 'reports.custom.transport_stats.export.excel'),
    ('director', 'reports.custom.finance_overview.view'),
    ('director', 'reports.custom.finance_overview.export.word'),
    ('director', 'reports.custom.finance_overview.export.excel'),
    ('director', 'reports.custom.employee_performance.view'),
    ('director', 'reports.custom.employee_performance.export.word'),
    ('director', 'reports.custom.employee_performance.export.excel'),

    -- manager
    ('manager', 'clients.list'),
    ('manager', 'clients.view'),
    ('manager', 'clients.orders_history.view'),
    ('manager', 'clients.orders_history.order.view'),
    ('manager', 'clients.attachments.view'),
    ('manager', 'clients.attachments.upload'),
    ('manager', 'clients.attachments.delete'),
    ('manager', 'orders.list'),
    ('manager', 'orders.view'),
    ('manager', 'orders.create'),
    ('manager', 'orders.edit'),
    ('manager', 'orders.export.pdf'),
    ('manager', 'orders.export.excel'),
    ('manager', 'orders.export.word'),
    ('manager', 'archive.orders.list'),
    ('manager', 'archive.orders.view'),
    ('manager', 'dashboard.view'),
    ('manager', 'dashboard.quick_actions.view'),
    ('manager', 'dashboard.summary.view'),
    ('manager', 'dashboard.sales_chart.view'),
    ('manager', 'dashboard.recent_orders.view'),
    ('manager', 'dashboard.finance_chart.view'),
    ('manager', 'dashboard.top_clients.view'),
    ('manager', 'reports.overview.view'),
    ('manager', 'reports.sales.view'),
    ('manager', 'reports.clients.view'),
    ('manager', 'reports.custom.view'),
    ('manager', 'reports.custom.clients_analysis.view'),
    ('manager', 'reports.custom.clients_analysis.export.word'),
    ('manager', 'reports.custom.clients_analysis.export.excel'),
    ('manager', 'reports.custom.missing_analysis.view'),
    ('manager', 'reports.custom.missing_analysis.export.word'),
    ('manager', 'reports.custom.missing_analysis.export.excel'),
    ('manager', 'reports.custom.sales_by_period.view'),
    ('manager', 'reports.custom.sales_by_period.export.word'),
    ('manager', 'reports.custom.sales_by_period.export.excel'),
    ('manager', 'clients.create'),
    ('manager', 'clients.edit'),

    -- purchaser
    ('purchaser', 'orders.purchases.create'),
    ('purchaser', 'purchases.list'),
    ('purchaser', 'purchases.view'),
    ('purchaser', 'purchases.create'),
    ('purchaser', 'purchases.edit'),
    ('purchaser', 'purchases.order.view'),
    ('purchaser', 'purchases.print'),
    ('purchaser', 'purchases.export.pdf'),
    ('purchaser', 'purchases.export.excel'),
    ('purchaser', 'purchases.export.word'),
    ('purchaser', 'purchases.attachments.view'),
    ('purchaser', 'purchases.attachments.upload'),
    ('purchaser', 'archive.purchases.list'),
    ('purchaser', 'archive.purchases.view'),
    ('purchaser', 'dashboard.view'),
    ('purchaser', 'dashboard.quick_actions.view'),
    ('purchaser', 'dashboard.top_products.view'),
    ('purchaser', 'reports.products.view'),
    ('purchaser', 'reports.custom.view'),
    ('purchaser', 'reports.custom.missing_analysis.view'),
    ('purchaser', 'reports.custom.missing_analysis.export.word'),
    ('purchaser', 'reports.custom.missing_analysis.export.excel'),
    ('purchaser', 'reports.custom.suppliers_analysis.view'),
    ('purchaser', 'reports.custom.suppliers_analysis.export.word'),
    ('purchaser', 'reports.custom.suppliers_analysis.export.excel'),
    ('purchaser', 'suppliers.create'),
    ('purchaser', 'suppliers.edit'),

    -- warehouse_manager
    ('warehouse_manager', 'warehouse.list'),
    ('warehouse_manager', 'warehouse.view'),
    ('warehouse_manager', 'warehouse.create'),
    ('warehouse_manager', 'warehouse.edit'),
    ('warehouse_manager', 'warehouse.delete'),
    ('warehouse_manager', 'warehouse.movement.create'),
    ('warehouse_manager', 'warehouse.stock.adjust'),
    ('warehouse_manager', 'warehouse.movements.view'),
    ('warehouse_manager', 'warehouse.critical.view'),
    ('warehouse_manager', 'warehouse.export.excel'),
    ('warehouse_manager', 'warehouse.import.excel'),
    ('warehouse_manager', 'warehouse.waiting_orders.view'),
    ('warehouse_manager', 'warehouse.pending_purchases.view'),
    ('warehouse_manager', 'warehouse-products.attachments.view'),
    ('warehouse_manager', 'warehouse-products.attachments.upload'),
    ('warehouse_manager', 'warehouse-products.attachments.delete'),
    ('warehouse_manager', 'dashboard.view'),
    ('warehouse_manager', 'dashboard.quick_actions.view'),
    ('warehouse_manager', 'dashboard.summary.view'),
    ('warehouse_manager', 'dashboard.stock_by_category.view'),
    ('warehouse_manager', 'dashboard.warehouse_movements.view'),
    ('warehouse_manager', 'dashboard.top_products.view'),
    ('warehouse_manager', 'reports.products.view'),
    ('warehouse_manager', 'reports.custom.view'),
    ('warehouse_manager', 'reports.custom.missing_analysis.view'),
    ('warehouse_manager', 'reports.custom.missing_analysis.export.word'),
    ('warehouse_manager', 'reports.custom.missing_analysis.export.excel'),
    ('warehouse_manager', 'reports.custom.warehouse_movements.view'),
    ('warehouse_manager', 'reports.custom.warehouse_movements.export.word'),
    ('warehouse_manager', 'reports.custom.warehouse_movements.export.excel'),

    -- logistics
    ('logistics', 'shipments.list'),
    ('logistics', 'shipments.view'),
    ('logistics', 'shipments.create'),
    ('logistics', 'shipments.edit'),
    ('logistics', 'shipments.ship'),
    ('logistics', 'shipments.order.view'),
    ('logistics', 'shipments.track'),
    ('logistics', 'shipments.print'),
    ('logistics', 'shipments.export.excel'),
    ('logistics', 'shipments.import.excel'),
    ('logistics', 'shipments.positions.view'),
    ('logistics', 'shipments.attachments.view'),
    ('logistics', 'shipments.attachments.upload'),
    ('logistics', 'shipments.attachments.delete'),
    ('logistics', 'archive.shipments.list'),
    ('logistics', 'archive.shipments.view'),
    ('logistics', 'dashboard.view'),
    ('logistics', 'dashboard.quick_actions.view'),
    ('logistics', 'dashboard.transport_performance.view'),
    ('logistics', 'reports.logistics.view'),
    ('logistics', 'reports.custom.view'),
    ('logistics', 'reports.custom.transport_stats.view'),
    ('logistics', 'reports.custom.transport_stats.export.word'),
    ('logistics', 'reports.custom.transport_stats.export.excel'),

    -- viewer

    -- accountant (безопасный базовый набор: просмотр + отчёты)
    ('accountant', 'archive.payments.list'),
    ('accountant', 'archive.finance.list'),
    ('accountant', 'dashboard.view'),
    ('accountant', 'dashboard.quick_actions.view'),
    ('accountant', 'dashboard.sales_chart.view'),
    ('accountant', 'dashboard.finance_chart.view'),
    ('accountant', 'dashboard.top_products.view'),
    ('accountant', 'dashboard.top_clients.view'),
    ('accountant', 'dashboard.transport_performance.view'),
    ('accountant', 'reports.overview.view'),
    ('accountant', 'reports.sales.view'),
    ('accountant', 'reports.products.view'),
    ('accountant', 'reports.clients.view'),
    ('accountant', 'reports.logistics.view'),
    ('accountant', 'reports.custom.view'),
    ('accountant', 'reports.custom.clients_analysis.view'),
    ('accountant', 'reports.custom.clients_analysis.export.word'),
    ('accountant', 'reports.custom.clients_analysis.export.excel'),
    ('accountant', 'reports.custom.missing_analysis.view'),
    ('accountant', 'reports.custom.missing_analysis.export.word'),
    ('accountant', 'reports.custom.missing_analysis.export.excel'),
    ('accountant', 'reports.custom.suppliers_analysis.view'),
    ('accountant', 'reports.custom.suppliers_analysis.export.word'),
    ('accountant', 'reports.custom.suppliers_analysis.export.excel'),
    ('accountant', 'reports.custom.warehouse_movements.view'),
    ('accountant', 'reports.custom.warehouse_movements.export.word'),
    ('accountant', 'reports.custom.warehouse_movements.export.excel'),
    ('accountant', 'reports.custom.sales_by_period.view'),
    ('accountant', 'reports.custom.sales_by_period.export.word'),
    ('accountant', 'reports.custom.sales_by_period.export.excel'),
    ('accountant', 'reports.custom.transport_stats.view'),
    ('accountant', 'reports.custom.transport_stats.export.word'),
    ('accountant', 'reports.custom.transport_stats.export.excel'),
    ('accountant', 'reports.custom.finance_overview.view'),
    ('accountant', 'reports.custom.finance_overview.export.word'),
    ('accountant', 'reports.custom.finance_overview.export.excel')
),
resolved AS (
  SELECT
    r.id AS role_id,
    p.id AS permission_id
  FROM src_role_perms s
  JOIN public.roles r ON r.key = s.role_key
  JOIN public.permissions p ON p.key = s.perm_key
)
INSERT INTO public.role_permissions(role_id, permission_id)
SELECT role_id, permission_id
FROM resolved
ON CONFLICT DO NOTHING;

-- 4) Назначение ролей пользователям по должности
WITH pos_role_map(position_norm, role_key) AS (
  VALUES
    ('главный директор', 'director'),
    ('менеджер по продажам', 'manager'),
    ('старший менеджер', 'manager'),
    ('менеджер по закупкам', 'purchaser'),
    ('заведующий складом', 'warehouse_manager'),
    ('логист', 'logistics'),
    ('бухгалтер', 'accountant')
),
candidates AS (
  SELECT
    u.id AS user_id,
    r.id AS role_id
  FROM public.users u
  JOIN public."Сотрудники" e ON e.id = u.employee_id
  JOIN pos_role_map m
    ON lower(trim(coalesce(e."должность", ''))) = m.position_norm
  JOIN public.roles r ON r.key = m.role_key
)
INSERT INTO public.user_roles(user_id, role_id)
SELECT user_id, role_id
FROM candidates
ON CONFLICT DO NOTHING;

COMMIT;
